### ISSUE TITLE
the script don't execute

### ISSUE THREAD

**Issue by KimeruReru** [hataori-p/real-voice#3]
![image](https://user-images.githubusercontent.com/57687094/153668650-f2869111-dff2-4cb4-ac80-448a2584cabe.png)

**Comment by KimeruReru** [comment]
![image](https://user-images.githubusercontent.com/57687094/153670900-03857f1e-0b93-454e-9caf-f5dffff94539.png)
also this

**Comment by hataori-p** [comment]
> ![image](https://user-images.githubusercontent.com/57687094/153668650-f2869111-dff2-4cb4-ac80-448a2584cabe.png)

Error - could not create config file

I see in the project name a Chinese / Kanji charcter - please, could you try to rename it with alphabet characters?
What operation system?

**Comment by KimeruReru** [comment]
the file is saved, it only happends on hiragana folders, romaji folders are fine
this bug is only for hiragana folders

**Comment by KimeruReru** [comment]
> > ![image](https://user-images.githubusercontent.com/57687094/153668650-f2869111-dff2-4cb4-ac80-448a2584cabe.png)
> 
> Error - could not create config file
> 
> I see in the project name a Chinese / Kanji charcter - please, could you try to rename it with alphabet characters? What operating system?
the file is saved, it only happends on hiragana folders, romaji folders are fine
this bug is only for hiragana folders
windows 10

**Comment by KimeruReru** [comment]
It still not working on hiragana folders,but now Works freely of saving the
file ir having a more complex name on the file
Also ALL hiragana svp now Works 100%
I was testing and some did not Works ( more than 7 letters idk why)

Em sáb, 12 de fev de 2022 17:47, hataori-p ***@***.***>
escreveu:
